export const CREATE_TASK = "CREATE_TASK"
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE"

export const RETRIEVE_TASK = "RETRIEVE_TASK"
export const RETRIEVE_TASK_SUCCESS = "RETRIEVE_TASK_SUCCESS"
export const RETRIEVE_TASK_FAILURE = "RETRIEVE_TASK_FAILURE"

export const UPDATE_TASK = "UPDATE_TASK"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE"

export const DELETE_TASK = "DELETE_TASK"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE"
